### ISSUE TITLE
add -l/--list to get a list of all the DMI strings

### ISSUE THREAD

**Issue by jczuluag** [jrgerber/dmidecode-rs#5]

**Comment by jczuluag** [comment]
Hi @jrgerber , what do you think about this approach?

**Comment by jrgerber** [comment]
There are some interesting things that structopt can do and it may be the
easiest way to do it.  For example, I saw that you can use structopt to add
more details to the main help page.  Also, I had tried the "subcommand"
attribute, applied to the "keyword" field in main.rs to see what it would
do, and it gave the output on the help page looking just like what you have
typed in.  The case is called "kebab case"... I might guess it is called
kebab because the "-" is used between the words and looks like someone put
a shish kebab through the words?

So I am suspecting there might be a structopt way to do it or something
similar?

I will have the same problem with -t --type (I have a branch for this work
right now too)...

I'm just finishing with the work day and will start looking at this.
Somewhere I found a github full of examples for structopt.... I need to
find that again.
